language: java

jdk:
  - oraclejdk9

matrix:
  include:
    - jdk: oraclejdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

script:
  - mvn clean test